export const REQUEST = '_REQUEST'
export const SUCCESS = '_SUCCESS'
export const FAILURE = '_FAILURE'

export const QUERY_INCOME_REPORT = 'QUERY_INCOME_REPORT'
export const QUERY_BUSINESS = 'QUERY_BUSINESS'
export const GET_REPORT_FORMINFO = 'GET_REPORT_FORMINFO'
